// frontend/app/chat/page.tsx
import { ChatWindow } from "@/components/ChatWindow";
import { Navbar } from "@/components/Navbar";
import { ScamTicker } from "@/components/ScamTicker";

export default function ChatPage() {
  return (
    <div>
      <ScamTicker />
      <Navbar />
      <main className="mx-auto max-w-5xl px-4 py-6">
        <div className="mb-4">
          <div className="text-xl font-semibold text-white">Chat</div>
          <div className="text-sm text-white/70">
            Fintech.AI replies in your selected language and always includes official reporting links.
          </div>
        </div>
        <ChatWindow />
      </main>
    </div>
  );
}

// frontend/src/app/pages/chat/chat.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-chat-page',
  templateUrl: './chat.component.html'
})
export class ChatPageComponent {}

<div>
  <app-scam-ticker></app-scam-ticker>
  <app-navbar></app-navbar>
  <main class="mx-auto max-w-5xl px-4 py-6">
    <div class="mb-4">
      <div class="text-xl font-semibold text-white">Chat</div>
      <div class="text-sm text-white/70">
        Fintech.AI replies in your selected language and always includes official reporting links.
      </div>
    </div>
    <app-chat-window></app-chat-window>
  </main>
</div>
