// frontend/src/app/components/scam-ticker/scam-ticker.component.ts
import { Component, OnInit, OnDestroy, signal, computed } from '@angular/core';
import { api, ScamAlert } from '../../core/api';

@Component({
  selector: 'app-scam-ticker',
  templateUrl: './scam-ticker.component.html'
})
export class ScamTickerComponent implements OnInit, OnDestroy {
  items = signal<ScamAlert[]>([]);
  error = signal<string | null>(null);
  
  private intervalId: any;

  text = computed(() => {
    if (this.error()) return "Trending Scams: unable to load right now.";
    const currentItems = this.items();
    if (!currentItems.length) return "Trending Scams in India Today: Loading…";
    const top = currentItems.slice(0, 6).map(x => x.title);
    return `Trending Scams in India Today: ${top.join(" • ")}`;
  });

  async refresh() {
    try {
      this.error.set(null);
      const res = await api.trendingScams();
      this.items.set(res.items || []);
    } catch (e: any) {
      this.error.set(e?.message || "Failed to load");
    }
  }

  ngOnInit() {
    this.refresh();
    this.intervalId = setInterval(() => this.refresh(), 30 * 60 * 1000);
  }

  ngOnDestroy() {
    if (this.intervalId) {
      clearInterval(this.intervalId);
    }
  }
}

<div class="border-b border-white/10 bg-black/20">
  <div class="mx-auto max-w-5xl px-4 py-2">
    <div class="truncate text-sm text-saffron">{{ text() }}</div>
  </div>
</div>

// frontend/components/ScamTicker.tsx
"use client";

import { useEffect, useMemo, useState } from "react";
import { api, ScamAlert } from "@/lib/api";

export function ScamTicker() {
  const [items, setItems] = useState<ScamAlert[]>([]);
  const [error, setError] = useState<string | null>(null);

  async function refresh() {
    try {
      setError(null);
      const res = await api.trendingScams();
      setItems(res.items || []);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Failed to load");
    }
  }

  useEffect(() => {
    refresh();
    const id = setInterval(refresh, 30 * 60 * 1000);
    return () => clearInterval(id);
  }, []);

  const text = useMemo(() => {
    if (error) return "Trending Scams: unable to load right now.";
    if (!items.length) return "Trending Scams in India Today: Loading…";
    const top = items.slice(0, 6).map((x) => x.title);
    return `Trending Scams in India Today: ${top.join(" • ")}`;
  }, [items, error]);

  return (
    <div className="border-b border-white/10 bg-black/20">
      <div className="mx-auto max-w-5xl px-4 py-2">
        <div className="truncate text-sm text-saffron">{text}</div>
      </div>
    </div>
  );
}
